# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20_models.ipynb.

# %% auto 0
__all__ = ['SimpleNet']

# %% ../nbs/20_models.ipynb 3
from .utils import *
from .dataloaders import *
from matplotlib import pyplot as plt

from fastcore.all import *
import torch
from torch import nn
from torch import Tensor
from datasets import load_dataset
from torch.utils.data import DataLoader
import torchvision.transforms.functional as TF
import pandas as pd 
import numpy as np
from datasets import Dataset

# %% ../nbs/20_models.ipynb 5
class SimpleNet(nn.Module):
    '''simple net'''
    def __init__(self,in_features,hidden_features, out_features):
        super().__init__()
        self.fc1 = nn.Linear(in_features,hidden_features)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_features,out_features)

    def forward(self,x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x