# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/60_tracking.ipynb.

# %% auto 0
__all__ = ['TrackingCB']

# %% ../nbs/60_tracking.ipynb 4
from .utils import *
from .dataloaders import *
from .models import *
from .training import *

from datetime import datetime,timedelta
import torchvision.transforms.functional as TF,torch.nn.functional as F

import matplotlib.pyplot as plt,matplotlib as mpl
import fastcore.all as fc
import torch
from torch import nn, Tensor
from datasets import load_dataset, Dataset
from torch.utils.data import DataLoader
import pandas as pd , numpy as np
from torcheval.metrics import MulticlassAccuracy,Mean
from fastprogress.fastprogress import master_bar, progress_bar

from pathlib import Path
import pandas as pd
import math

# %% ../nbs/60_tracking.ipynb 7
class TrackingCB:
    def __init__(self, db_path,exp_name):
        self._exp_name = exp_name
        self._log_epoch,self._log_batch, self._log_fit = [pd.DataFrame()]*3
        
    def before_fit(self,trainer):
        trainer.epochs = master_bar(trainer.epochs)
        if getattr(trainer,'MetricsCB',None) is not None: setattr(getattr(trainer,'MetricsCB'),'_log',self._log)
        log = {'model':str(trainer.model),'model_type':str(type(trainer.model)),'model_source':inspect.getsource(trainer.model.__class__)}
        log['callbacks'] = str(trainer.callbacks)

        for callback in trainer.callbacks:
            cb = getattr(trainer,callback)
            cb_attrs = dir(cb)
            for cb_attr in cb_attrs:
                if cb_attr.startswith('_'): continue
                if not callable(getattr(cb,cb_attr)): log[cb_attr] = str(getattr(cb,cb_attr))
        self._log(log)
    
    def before_batch(self,trainer): time.sleep(0.5)
    
    def before_train(self,trainer):
        trainer.batches = progress_bar(trainer.batches,parent=trainer.epochs)
        trainer.epochs.child.comment = "Training"
    def before_valid(self,trainer):
        trainer.batches = progress_bar(trainer.batches,parent=trainer.epochs)
        trainer.epochs.child.comment = "Validation"
        
    def _log(self,x):
        if 'elapsed' in x.keys(): x['elapsed'] = timedelta(seconds=math.ceil(x['elapsed'].total_seconds()))
        if isinstance(x,dict): x = PPDict(x)
        
        if 'epoch' in x.keys(): trainer.epochs.write(str(x))
        x['insert_timestamp'] = datetime.now()
        x['exp_name'] = self._exp_name
        log = pd.DataFrame(x,index=[""])
        if 'batch' in x.keys(): self._log_batch = pd.concat([self._log_batch,log])
        elif 'epoch' in x.keys(): self._log_epoch = pd.concat([self._log_epoch,log])
        else: self._log_fit = pd.concat([self._log_fit,log])
